<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <AssemblyName>FarmingSimulatorTelemetryClient</AssemblyName>
        <RootNamespace>FarmingSimulatorTelemetryClient</RootNamespace>
        <PackageId>FarmingSimulatorTelemetryClient</PackageId>
        <Title>Farming Simulator Telemetry Client</Title>
        <Authors>Casper Andesern&lt;Ndersorn@outlook.dk&gt;</Authors>
        <Description>Client for The FarmingSimulatorTelemetryServer Mod - Rewritten in DotnetCore and Avalonia</Description>
        <Copyright>Copyright © 2025</Copyright>
        <RepositoryUrl>https://github.com/ndersorn/FarmingSimulatorTelemetryMod</RepositoryUrl>
        <Company/>
        <Product>FarmingSimulatorTelemetryClient</Product>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
        <NeutralLanguage>en</NeutralLanguage>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <DefineConstants>DEBUG;TRACE</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.0" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.0" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.0" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.0" />
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.0">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>
</Project>
